// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZiApp.Infrastructure.Persistence;

#nullable disable

namespace ZiApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260830090137_InitialInvestmentLedger")]
    partial class InitialInvestmentLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZiApp.Domain.Accounts.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_user_accounts_normalized_email");

                    b.ToTable("user_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_accounts_preferred_language", "preferred_language IN ('English', 'Ukrainian', 'Russian')");

                            t.HasCheckConstraint("ck_user_accounts_role", "role IN ('User', 'SuperAdmin')");
                        });
                });

            modelBuilder.Entity("ZiApp.Domain.ExchangeRates.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<decimal>("RateToUah")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("rate_to_uah");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at_utc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_exchange_rates");

                    b.HasIndex("CurrencyCode", "EffectiveDate", "Source")
                        .IsUnique()
                        .HasDatabaseName("ux_exchange_rates_currency_date_source");

                    b.ToTable("exchange_rates", null, t =>
                        {
                            t.HasCheckConstraint("ck_exchange_rates_rate_to_uah", "rate_to_uah > 0");
                        });
                });

            modelBuilder.Entity("ZiApp.Domain.Instruments.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("exchange_code");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("character(12)")
                        .HasColumnName("isin")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasDatabaseName("ux_instruments_isin")
                        .HasFilter("isin IS NOT NULL");

                    b.HasIndex("Symbol", "ExchangeCode")
                        .IsUnique()
                        .HasDatabaseName("ux_instruments_symbol_exchange_code");

                    b.ToTable("instruments", null, t =>
                        {
                            t.HasCheckConstraint("ck_instruments_type", "type IN ('Stock', 'Etf')");
                        });
                });

            modelBuilder.Entity("ZiApp.Domain.Instruments.StockSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Denominator")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("denominator");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at_utc");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("Numerator")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("numerator");

                    b.HasKey("Id")
                        .HasName("pk_stock_splits");

                    b.HasIndex("InstrumentId", "EffectiveAtUtc", "Id")
                        .HasDatabaseName("ix_stock_splits_instrument_effective_order");

                    b.ToTable("stock_splits", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_splits_changes_units", "numerator <> denominator");

                            t.HasCheckConstraint("ck_stock_splits_denominator", "denominator > 0");

                            t.HasCheckConstraint("ck_stock_splits_numerator", "numerator > 0");
                        });
                });

            modelBuilder.Entity("ZiApp.Domain.Portfolios.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("base_currency_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("OwnerAccountId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_portfolios_owner_account_id_name");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("ZiApp.Domain.TaxReports.TaxCalculationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("calculation_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer")
                        .HasColumnName("tax_year");

                    b.HasKey("Id")
                        .HasName("pk_tax_calculation_runs");

                    b.HasIndex("PortfolioId", "TaxYear", "CreatedAtUtc")
                        .HasDatabaseName("ix_tax_calculation_runs_portfolio_year_created");

                    b.ToTable("tax_calculation_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_tax_calculation_runs_tax_year", "tax_year BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("ZiApp.Domain.TaxReports.TaxLotMatchSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ExpensesUah")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("expenses_uah");

                    b.Property<decimal>("ExpensesUsd")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("expenses_usd");

                    b.Property<decimal>("GrossDifferenceUah")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("gross_difference_uah");

                    b.Property<decimal>("GrossDifferenceUsd")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("gross_difference_usd");

                    b.Property<decimal>("MatchedQuantity")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("matched_quantity");

                    b.Property<decimal>("ProfitUah")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("profit_uah");

                    b.Property<decimal>("ProfitUsd")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("profit_usd");

                    b.Property<decimal>("PurchaseCostUah")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("purchase_cost_uah");

                    b.Property<decimal>("PurchaseCostUsd")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("purchase_cost_usd");

                    b.Property<decimal>("PurchaseFeeUah")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("purchase_fee_uah");

                    b.Property<decimal>("PurchaseFeeUsd")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("purchase_fee_usd");

                    b.Property<Guid>("PurchaseTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_transaction_id");

                    b.Property<decimal>("SaleFeeUah")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("sale_fee_uah");

                    b.Property<decimal>("SaleFeeUsd")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("sale_fee_usd");

                    b.Property<decimal>("SaleProceedsUah")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("sale_proceeds_uah");

                    b.Property<decimal>("SaleProceedsUsd")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("sale_proceeds_usd");

                    b.Property<Guid>("SaleTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_transaction_id");

                    b.Property<Guid>("TaxCalculationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_calculation_run_id");

                    b.HasKey("Id")
                        .HasName("pk_tax_lot_match_snapshots");

                    b.HasIndex("PurchaseTransactionId")
                        .HasDatabaseName("ix_tax_lot_matches_purchase_transaction_id");

                    b.HasIndex("SaleTransactionId")
                        .HasDatabaseName("ix_tax_lot_matches_sale_transaction_id");

                    b.HasIndex("TaxCalculationRunId", "PurchaseTransactionId", "SaleTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_tax_lot_matches_run_purchase_sale");

                    b.ToTable("tax_lot_match_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_tax_lot_match_snapshots_quantity", "matched_quantity > 0");
                        });
                });

            modelBuilder.Entity("ZiApp.Domain.Transactions.InvestmentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrokerTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("broker_transaction_id");

                    b.Property<Guid>("ExchangeRateId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_rate_id");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<decimal>("FeeUsd")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("fee_usd");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("side");

                    b.Property<decimal>("UnitPriceUsd")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("unit_price_usd");

                    b.HasKey("Id")
                        .HasName("pk_investment_transactions");

                    b.HasIndex("ExchangeRateId")
                        .HasDatabaseName("ix_investment_transactions_exchange_rate_id");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_investment_transactions_instrument_id");

                    b.HasIndex("PortfolioId", "BrokerTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_investment_transactions_portfolio_broker_id")
                        .HasFilter("broker_transaction_id IS NOT NULL");

                    b.HasIndex("PortfolioId", "ExecutedAtUtc", "Id")
                        .HasDatabaseName("ix_investment_transactions_fifo_order");

                    b.ToTable("investment_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_investment_transactions_fee_usd", "fee_usd >= 0");

                            t.HasCheckConstraint("ck_investment_transactions_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_investment_transactions_side", "side IN ('Buy', 'Sell')");

                            t.HasCheckConstraint("ck_investment_transactions_unit_price_usd", "unit_price_usd > 0");
                        });
                });

            modelBuilder.Entity("ZiApp.Domain.Instruments.StockSplit", b =>
                {
                    b.HasOne("ZiApp.Domain.Instruments.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_splits_instruments_instrument_id");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("ZiApp.Domain.Portfolios.Portfolio", b =>
                {
                    b.HasOne("ZiApp.Domain.Accounts.UserAccount", "OwnerAccount")
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolios_user_accounts_owner_account_id");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("ZiApp.Domain.TaxReports.TaxCalculationRun", b =>
                {
                    b.HasOne("ZiApp.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tax_calculation_runs_portfolios_portfolio_id");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("ZiApp.Domain.TaxReports.TaxLotMatchSnapshot", b =>
                {
                    b.HasOne("ZiApp.Domain.Transactions.InvestmentTransaction", "PurchaseTransaction")
                        .WithMany()
                        .HasForeignKey("PurchaseTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tax_lot_matches_transactions_purchase_id");

                    b.HasOne("ZiApp.Domain.Transactions.InvestmentTransaction", "SaleTransaction")
                        .WithMany()
                        .HasForeignKey("SaleTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tax_lot_matches_transactions_sale_id");

                    b.HasOne("ZiApp.Domain.TaxReports.TaxCalculationRun", "TaxCalculationRun")
                        .WithMany()
                        .HasForeignKey("TaxCalculationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tax_lot_matches_tax_calculation_runs_run_id");

                    b.Navigation("PurchaseTransaction");

                    b.Navigation("SaleTransaction");

                    b.Navigation("TaxCalculationRun");
                });

            modelBuilder.Entity("ZiApp.Domain.Transactions.InvestmentTransaction", b =>
                {
                    b.HasOne("ZiApp.Domain.ExchangeRates.ExchangeRate", "ExchangeRate")
                        .WithMany()
                        .HasForeignKey("ExchangeRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_investment_transactions_exchange_rates_exchange_rate_id");

                    b.HasOne("ZiApp.Domain.Instruments.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_investment_transactions_instruments_instrument_id");

                    b.HasOne("ZiApp.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_investment_transactions_portfolios_portfolio_id");

                    b.Navigation("ExchangeRate");

                    b.Navigation("Instrument");

                    b.Navigation("Portfolio");
                });
#pragma warning restore 612, 618
        }
    }
}
