<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ZiApp.Domain\ZiApp.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Accounts\" />
    <Folder Include="Security\" />
    <Compile Update="**\*.cs">
      <Visible>true</Visible>
    </Compile>
  </ItemGroup>

</Project>
